config/routes.rb
Rails.application.routes.draw do
  get 'inflows/idordered'
  get 'outflows/idordered'

  devise_for :users
  resources :inflowtypes
  resources :outflowtypes
  resources :outflows
  resources :people
  resources :bankaccounts
  resources :cashflows
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  resources :inflows
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

    @visitor_view_desc = "    CF Analyser allows authorised users to edit and review cash-flow data. It provides a user
interface that allows the user to easily navigate through transactions.  It is tailored to the cashflow module of HomeIntel.
To get access, please click on the request access button on the HomeIntel App Homepage.  Please note that only authorised users are allowed to access
this application. This is a private application with access to private data (Herga Privacy Policy). "

    @notice_of_access_request= "Access can only be requested via the HomeIntel Homepage."

    @inflows_f_followup = "All incomes of the household are captured on this table. Filtered by follow-up status "
    @inflows_f_transaid = "All incomes of the household are captured on this table. Filtered by transaction ID "
    @outflows_f_followup = "All expenses of the household are captured on this table. Filtered by follow-up status "
    @outflows_f_tansaid = "All expenses of the household are captured on this table. Filtered by transaction ID "



    @inflow_fu_count    = Inflow.where(follow_up: true).count
    @outflow_fu_count   = Outflow.where(follow_up: true).count

  end



  def help
    @help_information = " For All technical issues, users are required to contact the Herga Home Network administrator on  085 101 26 54.
All technical Issues are dealt with based on priority."
    @help_notice = "Contact Network Administrator on 085 101 2654 or herga.a@outlook.com"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<div class="jumbotron" style="background-color: #2a4b51">
  <div class="breadcrumb" style="background-color: khaki">
    <h2>CF Analyser - Help</h2>
  </div>
  <div class="jumbotron">
    <%=  @help_information %>
  </div>

  <div class="breadcrumb" style="background-color: khaki; color: #730E15">
    <%= @help_notice %>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if current_user %>

  <div class="jumbotron" style="background-color: #2a4b51">
    <div class="jumbotron">

      <div>
        <% if @inflow_fu_count == 0 && @outflow_fu_count == 0 %>
          <div class="breadcrumb" style="background-color: darkgreen;color: white">
            <h5>Great - <%= @inflow_fu_count %> income record(s) and <%= @outflow_fu_count %> expense record(s) to follow-up!</h5>
          </div>
        <% else %>
          <div class="breadcrumb"style="background-color: darkred;color: white">
            <h5>Warning - <%= @inflow_fu_count %> income record(s) and <%= @outflow_fu_count %> expense record(s) to follow-up! </h5>
          </div>
        <% end %>
      </div>

      <div class="breadcrumb" style="background-color: khaki">
        Cash-Flow Module
      </div>
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Table</th>
          <th>Description</th>

        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= link_to "Cash Inflows [Filter= Follow-up]", inflows_path %></td>
          <td> <%= @inflows_f_followup %></td>
        </tr>
        <tr>
          <td><%= link_to "Cash Inflows [Filster= Trans. Id]", inflows_idordered_path %></td>
          <td> <%= @inflows_f_transaid %></td>
        </tr>
        <tr>
          <td><%= link_to "Cash Outflows [Filter= Follow-up]", outflows_path %></td>
          <td><%= @outflows_f_followup %></td>
        </tr>
        <tr>
          <td><%= link_to "Cash Outflows [Filster= Trans. Id]", outflows_idordered_path %></td>
          <td><%= @outflows_f_tansaid %></td>
        </tr>

        </tbody>
      </table>
    </div>

    <div class="jumbotron">
      <div class="breadcrumb" style="background-color: khaki">
        Related Cash-flows
      </div>
      <table class="table table-hover">
        <thead>
        <tr>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= link_to "Cashflows", cashflows_path %></td>
        </tr>
        </tbody>
      </table>

    </div>

  </div>

<% else %>

  <div class="jumbotron" style="background-color: #2a4b51">
    <div class="breadcrumb" style="background-color: khaki">
      <h2>CF Analyser</h2>
    </div>
  <div class="jumbotron">
      <%= @visitor_view_desc %>
  </div>

  <div class="breadcrumb" style="background-color: khaki; color: #730E15">
      <%= @notice_of_access_request %>
  </div>

<% end %>

</div>