config/routes.rb
Rails.application.routes.draw do
  get 'inflows/idordered'
  get 'outflows/idordered'

  devise_for :users
  resources :inflowtypes
  resources :outflowtypes
  resources :outflows
  resources :people
  resources :bankaccounts
  resources :cashflows
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  resources :inflows
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/outflowtypes_controller.rb
class OutflowtypesController < ApplicationController
  before_action :set_outflowtype, only: [:show, :edit, :update, :destroy]

  # GET /outflowtypes
  # GET /outflowtypes.json
  def index
    @outflowtypes = Outflowtype.all
  end

  # GET /outflowtypes/1
  # GET /outflowtypes/1.json
  def show
  end

  # GET /outflowtypes/new
  def new
    @outflowtype = Outflowtype.new
  end

  # GET /outflowtypes/1/edit
  def edit
  end

  # POST /outflowtypes
  # POST /outflowtypes.json
  def create
    @outflowtype = Outflowtype.new(outflowtype_params)

    respond_to do |format|
      if @outflowtype.save
        format.html { redirect_to @outflowtype, notice: 'Outflowtype was successfully created.' }
        format.json { render :show, status: :created, location: @outflowtype }
      else
        format.html { render :new }
        format.json { render json: @outflowtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outflowtypes/1
  # PATCH/PUT /outflowtypes/1.json
  def update
    respond_to do |format|
      if @outflowtype.update(outflowtype_params)
        format.html { redirect_to @outflowtype, notice: 'Outflowtype was successfully updated.' }
        format.json { render :show, status: :ok, location: @outflowtype }
      else
        format.html { render :edit }
        format.json { render json: @outflowtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outflowtypes/1
  # DELETE /outflowtypes/1.json
  def destroy
    @outflowtype.destroy
    respond_to do |format|
      format.html { redirect_to outflowtypes_url, notice: 'Outflowtype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outflowtype
      @outflowtype = Outflowtype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outflowtype_params
      params.require(:outflowtype).permit(:name, :description, :system_item, :active)
    end
end

app/helpers/outflowtypes_helper.rb
module OutflowtypesHelper
end

app/views/outflowtypes/_form.html.erb
<%= form_with(model: outflowtype, local: true) do |form| %>
  <% if outflowtype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(outflowtype.errors.count, "error") %> prohibited this outflowtype from being saved:</h2>

      <ul>
      <% outflowtype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :system_item %>
    <%= form.check_box :system_item %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/outflowtypes/edit.html.erb
<h1>Editing Outflowtype</h1>

<%= render 'form', outflowtype: @outflowtype %>

<%= link_to 'Show', @outflowtype %> |
<%= link_to 'Back', outflowtypes_path %>

app/views/outflowtypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Outflowtypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>System item</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outflowtypes.each do |outflowtype| %>
      <tr>
        <td><%= outflowtype.name %></td>
        <td><%= outflowtype.description %></td>
        <td><%= outflowtype.system_item %></td>
        <td><%= outflowtype.active %></td>
        <td><%= link_to 'Show', outflowtype %></td>
        <td><%= link_to 'Edit', edit_outflowtype_path(outflowtype) %></td>
        <td><%= link_to 'Destroy', outflowtype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outflowtype', new_outflowtype_path %>

app/views/outflowtypes/new.html.erb
<h1>New Outflowtype</h1>

<%= render 'form', outflowtype: @outflowtype %>

<%= link_to 'Back', outflowtypes_path %>

app/views/outflowtypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @outflowtype.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @outflowtype.description %>
</p>

<p>
  <strong>System item:</strong>
  <%= @outflowtype.system_item %>
</p>

<p>
  <strong>Active:</strong>
  <%= @outflowtype.active %>
</p>

<%= link_to 'Edit', edit_outflowtype_path(@outflowtype) %> |
<%= link_to 'Back', outflowtypes_path %>