config/routes.rb
Rails.application.routes.draw do
  get 'inflows/idordered'
  get 'outflows/idordered'

  devise_for :users
  resources :inflowtypes
  resources :outflowtypes
  resources :outflows
  resources :people
  resources :bankaccounts
  resources :cashflows
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  resources :inflows
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/inflowtypes_controller.rb
class InflowtypesController < ApplicationController
  before_action :set_inflowtype, only: [:show, :edit, :update, :destroy]

  # GET /inflowtypes
  # GET /inflowtypes.json
  def index
    @inflowtypes = Inflowtype.all
  end

  # GET /inflowtypes/1
  # GET /inflowtypes/1.json
  def show
  end

  # GET /inflowtypes/new
  def new
    @inflowtype = Inflowtype.new
  end

  # GET /inflowtypes/1/edit
  def edit
  end

  # POST /inflowtypes
  # POST /inflowtypes.json
  def create
    @inflowtype = Inflowtype.new(inflowtype_params)

    respond_to do |format|
      if @inflowtype.save
        format.html { redirect_to @inflowtype, notice: 'Inflowtype was successfully created.' }
        format.json { render :show, status: :created, location: @inflowtype }
      else
        format.html { render :new }
        format.json { render json: @inflowtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inflowtypes/1
  # PATCH/PUT /inflowtypes/1.json
  def update
    respond_to do |format|
      if @inflowtype.update(inflowtype_params)
        format.html { redirect_to @inflowtype, notice: 'Inflowtype was successfully updated.' }
        format.json { render :show, status: :ok, location: @inflowtype }
      else
        format.html { render :edit }
        format.json { render json: @inflowtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inflowtypes/1
  # DELETE /inflowtypes/1.json
  def destroy
    @inflowtype.destroy
    respond_to do |format|
      format.html { redirect_to inflowtypes_url, notice: 'Inflowtype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inflowtype
      @inflowtype = Inflowtype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inflowtype_params
      params.require(:inflowtype).permit(:name, :description, :system_item, :active)
    end
end

app/helpers/inflowtypes_helper.rb
module InflowtypesHelper
end

app/views/inflowtypes/_form.html.erb
<%= form_with(model: inflowtype, local: true) do |form| %>
  <% if inflowtype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inflowtype.errors.count, "error") %> prohibited this inflowtype from being saved:</h2>

      <ul>
      <% inflowtype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :system_item %>
    <%= form.check_box :system_item %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inflowtypes/edit.html.erb
<h1>Editing Inflowtype</h1>

<%= render 'form', inflowtype: @inflowtype %>

<%= link_to 'Show', @inflowtype %> |
<%= link_to 'Back', inflowtypes_path %>

app/views/inflowtypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inflowtypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>System item</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inflowtypes.each do |inflowtype| %>
      <tr>
        <td><%= inflowtype.name %></td>
        <td><%= inflowtype.description %></td>
        <td><%= inflowtype.system_item %></td>
        <td><%= inflowtype.active %></td>
        <td><%= link_to 'Show', inflowtype %></td>
        <td><%= link_to 'Edit', edit_inflowtype_path(inflowtype) %></td>
        <td><%= link_to 'Destroy', inflowtype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inflowtype', new_inflowtype_path %>

app/views/inflowtypes/new.html.erb
<h1>New Inflowtype</h1>

<%= render 'form', inflowtype: @inflowtype %>

<%= link_to 'Back', inflowtypes_path %>

app/views/inflowtypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inflowtype.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @inflowtype.description %>
</p>

<p>
  <strong>System item:</strong>
  <%= @inflowtype.system_item %>
</p>

<p>
  <strong>Active:</strong>
  <%= @inflowtype.active %>
</p>

<%= link_to 'Edit', edit_inflowtype_path(@inflowtype) %> |
<%= link_to 'Back', inflowtypes_path %>